// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mira.Infrastructure.DbContexts;

#nullable disable

namespace Mira.Infrastructure.Migrations
{
    [DbContext(typeof(MiraContext))]
    partial class MiraContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mira.Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("Items", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Mira.Domain.Entities.ItemDocument", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("LinkedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("ItemId", "DocumentId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("ItemId", "Role")
                        .IsUnique()
                        .HasFilter("[Role] = 'PrimaryImage'");

                    b.ToTable("ItemDocuments", null, t =>
                        {
                            t.HasCheckConstraint("CK_ItemDocuments_NoSelfReference", "[ItemId] <> [DocumentId]");
                        });
                });

            modelBuilder.Entity("Mira.Domain.Entities.Asset", b =>
                {
                    b.HasBaseType("Mira.Domain.Entities.Item");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("CurrentValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("PurchaseDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("PurchasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Seller")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasIndex("SerialNumber");

                    b.ToTable("Assets", null, t =>
                        {
                            t.HasCheckConstraint("CK_Assets_CurrentValue_NonNegative", "[CurrentValue] IS NULL OR [CurrentValue] >= 0");

                            t.HasCheckConstraint("CK_Assets_PurchasePrice_NonNegative", "[PurchasePrice] IS NULL OR [PurchasePrice] >= 0");
                        });
                });

            modelBuilder.Entity("Mira.Domain.Entities.Contract", b =>
                {
                    b.HasBaseType("Mira.Domain.Entities.Item");

                    b.Property<bool>("AutomaticallyRenews")
                        .HasColumnType("bit");

                    b.Property<string>("BillingFrequency")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateOnly?>("CancellationDeadline")
                        .HasColumnType("date");

                    b.Property<int?>("CancellationNoticeDays")
                        .HasColumnType("int");

                    b.Property<string>("ContractNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContractParty")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("EndsOn")
                        .HasColumnType("date");

                    b.Property<int?>("RenewalPeriodMonths")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date");

                    b.HasIndex("CancellationDeadline");

                    b.HasIndex("EndsOn");

                    b.ToTable("Contracts", null, t =>
                        {
                            t.HasCheckConstraint("CK_Contracts_CancellationNoticeDays_NonNegative", "[CancellationNoticeDays] IS NULL OR [CancellationNoticeDays] >= 0");

                            t.HasCheckConstraint("CK_Contracts_Cost_NonNegative", "[Cost] IS NULL OR [Cost] >= 0");

                            t.HasCheckConstraint("CK_Contracts_RenewalPeriodMonths_Positive", "[RenewalPeriodMonths] IS NULL OR [RenewalPeriodMonths] > 0");
                        });
                });

            modelBuilder.Entity("Mira.Domain.Entities.Document", b =>
                {
                    b.HasBaseType("Mira.Domain.Entities.Item");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("ExpiresOn")
                        .HasColumnType("date");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("IssuedOn")
                        .HasColumnType("date");

                    b.Property<string>("Issuer")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasIndex("Checksum");

                    b.HasIndex("ExpiresOn");

                    b.ToTable("Documents", null, t =>
                        {
                            t.HasCheckConstraint("CK_Documents_FileSizeBytes_Positive", "[FileSizeBytes] > 0");
                        });
                });

            modelBuilder.Entity("Mira.Domain.Entities.Subscription", b =>
                {
                    b.HasBaseType("Mira.Domain.Entities.Item");

                    b.Property<bool>("AutomaticallyRenews")
                        .HasColumnType("bit");

                    b.Property<string>("BillingFrequency")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("CancellationNoticeDays")
                        .HasColumnType("int");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("NextBillingDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("TrialEndsOn")
                        .HasColumnType("date");

                    b.HasIndex("ContractId");

                    b.HasIndex("NextBillingDate");

                    b.ToTable("Subscriptions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Subscriptions_CancellationNoticeDays_NonNegative", "[CancellationNoticeDays] IS NULL OR [CancellationNoticeDays] >= 0");

                            t.HasCheckConstraint("CK_Subscriptions_Price_NonNegative", "[Price] >= 0");
                        });
                });

            modelBuilder.Entity("Mira.Domain.Entities.Warranty", b =>
                {
                    b.HasBaseType("Mira.Domain.Entities.Item");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClaimInstructions")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateOnly>("EndsOn")
                        .HasColumnType("date");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date");

                    b.Property<string>("Terms")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("WarrantyType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasIndex("AssetId");

                    b.HasIndex("EndsOn");

                    b.ToTable("Warranties", null, t =>
                        {
                            t.HasCheckConstraint("CK_Warranties_DateRange", "[EndsOn] >= [StartsOn]");
                        });
                });

            modelBuilder.Entity("Mira.Domain.Entities.ItemDocument", b =>
                {
                    b.HasOne("Mira.Domain.Entities.Document", "Document")
                        .WithMany("ItemLinks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mira.Domain.Entities.Item", "Item")
                        .WithMany("DocumentLinks")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Mira.Domain.Entities.Asset", b =>
                {
                    b.HasOne("Mira.Domain.Entities.Item", null)
                        .WithOne()
                        .HasForeignKey("Mira.Domain.Entities.Asset", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mira.Domain.Entities.Contract", b =>
                {
                    b.HasOne("Mira.Domain.Entities.Item", null)
                        .WithOne()
                        .HasForeignKey("Mira.Domain.Entities.Contract", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mira.Domain.Entities.Document", b =>
                {
                    b.HasOne("Mira.Domain.Entities.Item", null)
                        .WithOne()
                        .HasForeignKey("Mira.Domain.Entities.Document", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mira.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("Mira.Domain.Entities.Contract", "Contract")
                        .WithMany("Subscriptions")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Mira.Domain.Entities.Item", null)
                        .WithOne()
                        .HasForeignKey("Mira.Domain.Entities.Subscription", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("Mira.Domain.Entities.Warranty", b =>
                {
                    b.HasOne("Mira.Domain.Entities.Asset", "Asset")
                        .WithMany("Warranties")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mira.Domain.Entities.Item", null)
                        .WithOne()
                        .HasForeignKey("Mira.Domain.Entities.Warranty", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Mira.Domain.Entities.Item", b =>
                {
                    b.Navigation("DocumentLinks");
                });

            modelBuilder.Entity("Mira.Domain.Entities.Asset", b =>
                {
                    b.Navigation("Warranties");
                });

            modelBuilder.Entity("Mira.Domain.Entities.Contract", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Mira.Domain.Entities.Document", b =>
                {
                    b.Navigation("ItemLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
